server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webmvc:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth/**
            - id: patient-service
              uri: lb://PATIENT-SERVICE
              predicates:
                - Path=/patients/**
            - id: doctor-service-doctors
              uri: lb://DOCTOR-SERVICE
              predicates:
                - Path=/doctors/**
            - id: doctor-service-departments
              uri: lb://DOCTOR-SERVICE
              predicates:
                - Path=/departments/**
            - id: doctor-service-slots
              uri: lb://DOCTOR-SERVICE
              predicates:
                - Path=/slots/**

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8761/eureka

jwt:
  secret: mysecretkeymysecretkeymysecretkey
