server:
  port: 8088

spring:
  application:
    name: pharmacy-service

  datasource:
    url: jdbc:postgresql://postgres:5432/hms_pharmacy_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:2131}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:kafka:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://service-registry:8761/eureka}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

hms:
  topics:
    stock-low: stock_low
